plugins {
    id 'com.android.application'
}

android {
    namespace "com.example.abcplayer"
    compileSdk 34

    defaultConfig {
        applicationId "com.example.abcplayer"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'org.jtransforms:jtransforms:2.4.0'
}
